### PR TITLE
Feat/untagged resources

### PR DESCRIPTION
**Pull request by cruffinoni**
Split PR#230 (https://github.com/trackit/trackit/pull/230) - Part 1 
This branch is reserved for the feature.

### CODE REVIEW

**Comment by cruffinoni** [comment]
The branch hasn't been tested yet.

**Comment by Dr0p42** [comment]
@cruffinoni let us know when this pull request has been tested and is ready to review ;)

**Comment by Dr0p42** [comment]
Blocked because we don't have a pagination mechanism with Elasticsearch. To be brainstormed by @hug33k @giubil @thibautcornolti @jgchoppe @cruffinoni 

This comment is just to keep track, no worries ;)

**Comment by Dr0p42** [comment]
> Blocked because we don't have a pagination mechanism with Elasticsearch. To be brainstormed by @hug33k @giubil @thibautcornolti @jgchoppe @cruffinoni
> 
> This comment is just to keep track, no worries ;)

@hug33k any news about this ?

**Comment by simonmeyerrr** [comment]
@Dr0p42 @hug33k : I found a solution to decrease the size of Aggregation queries. I use "partitions" that allow to paginate the aggregations. It works correctly and there is no data loss. I don't know the specific cases that were problematic, so I'll let you test this upgrade on this cases when you have the time.

**Comment by alexandre-snr** [comment]
This PR is now redundant with tagbot

**Pull request closed without merging**
